[package]
authors = ["Jorge Aparicio <jorge@japaric.io>", "Dylan Frankland <dylan@frankland.io"]
categories = ["embedded", "hardware-support", "no-std"]
description = "Peripheral access API for STM32F3 series microcontrollers"
keywords = ["arm", "cortex-m", "stm32f3xx", "hal"]
license = "0BSD"
name = "stm32f3xx-hal"
repository = "https://github.com/dfrankalnd/stm32f3xx-hal"
version = "0.1.0"

[dependencies]
cortex-m = "0.5.0"
embedded-hal = "0.2.0"
nb = "0.1.0"
stm32f30x = "0.7.0"

[dependencies.void]
default-features = false
version = "1.0.2"

[dependencies.cast]
default-features = false
version = "0.2.2"

[features]
rt = ["stm32f30x/rt"]
